### ISSUE TITLE
http3 protocol error: Application error 0x100 (remote): reached maximum number of requests

### ISSUE THREAD

**Issue by Donghui0** [linkxzhou/http_bench#7]
The http3 protocol is used for stress testing, and the target end is nginx. An error is reported even when initiating a request.

./http_bench   -c 1 -n 1000 -http http3 -m GET  'https://xxx:9443'

**Comment by linkxzhou** [comment]
This bug is similar to this issue: https://github.com/quic-go/quic-go/issues/2287.

And

I resolved the current issue by upgrading the quic library. Please use the latest version.
